import type { KeyInput } from 'puppeteer-core';

export function convertBrowserKeyToken(key: string, isMac = false): KeyInput {
  const lowerKey = key.trim().toLowerCase().replace(/_/g, '').replace(/\s+/g, '');

  if (isMac) {
    if (lowerKey === 'control' || lowerKey === 'ctrl') {
      return 'Meta' as KeyInput;
    }
    if (lowerKey === 'command' || lowerKey === 'cmd') {
      return 'Meta' as KeyInput;
    }
    if (lowerKey === 'option' || lowerKey === 'opt') {
      return 'Alt' as KeyInput;
    }
  }

  const keyMap: Record<string, KeyInput> = {
    a: 'KeyA',
    b: 'KeyB',
    c: 'KeyC',
    d: 'KeyD',
    e: 'KeyE',
    f: 'KeyF',
    g: 'KeyG',
    h: 'KeyH',
    i: 'KeyI',
    j: 'KeyJ',
    k: 'KeyK',
    l: 'KeyL',
    m: 'KeyM',
    n: 'KeyN',
    o: 'KeyO',
    p: 'KeyP',
    q: 'KeyQ',
    r: 'KeyR',
    s: 'KeyS',
    t: 'KeyT',
    u: 'KeyU',
    v: 'KeyV',
    w: 'KeyW',
    x: 'KeyX',
    y: 'KeyY',
    z: 'KeyZ',
    '0': 'Digit0',
    '1': 'Digit1',
    '2': 'Digit2',
    '3': 'Digit3',
    '4': 'Digit4',
    '5': 'Digit5',
    '6': 'Digit6',
    '7': 'Digit7',
    '8': 'Digit8',
    '9': 'Digit9',
    control: 'Control',
    ctrl: 'Control',
    shift: 'Shift',
    alt: 'Alt',
    meta: 'Meta',
    super: 'Meta',
    command: 'Meta',
    cmd: 'Meta',
    option: 'Alt',
    opt: 'Alt',
    enter: 'Enter',
    return: 'Enter',
    backspace: 'Backspace',
    delete: 'Delete',
    insert: 'Insert',
    home: 'Home',
    end: 'End',
    pageup: 'PageUp',
    pagedown: 'PageDown',
    arrowleft: 'ArrowLeft',
    arrowright: 'ArrowRight',
    arrowup: 'ArrowUp',
    arrowdown: 'ArrowDown',
    left: 'ArrowLeft',
    right: 'ArrowRight',
    up: 'ArrowUp',
    down: 'ArrowDown',
    escape: 'Escape',
    esc: 'Escape',
    tab: 'Tab',
    space: 'Space',
    capslock: 'CapsLock',
    f1: 'F1',
    f2: 'F2',
    f3: 'F3',
    f4: 'F4',
    f5: 'F5',
    f6: 'F6',
    f7: 'F7',
    f8: 'F8',
    f9: 'F9',
    f10: 'F10',
    f11: 'F11',
    f12: 'F12',
    minus: 'Minus',
    hyphen: 'Minus',
    dash: 'Minus',
    '-': 'Minus',
    equal: 'Equal',
    equals: 'Equal',
    '=': 'Equal',
    plus: 'Plus',
    '+': 'Plus',
    period: 'Period',
    '.': 'Period',
    comma: 'Comma',
    ',': 'Comma',
    slash: 'Slash',
    '/': 'Slash',
    backslash: 'Backslash',
    '\\': 'Backslash',
    semicolon: 'Semicolon',
    ';': 'Semicolon',
    quote: 'Quote',
    "'": 'Quote',
    backquote: 'Backquote',
    '`': 'Backquote',
    bracketleft: 'BracketLeft',
    '[': 'BracketLeft',
    bracketright: 'BracketRight',
    ']': 'BracketRight',
  };

  return keyMap[lowerKey] ?? (key as KeyInput);
}
